#include <omnetpy.h>

Define_Python_Module("txc1", "PyTxc1");
Define_Python_Module("txc2", "PyTxc2");
Define_Python_Module("txc3", "PyTxc3");
Define_Python_Module("txc4", "PyTxc4");
Define_Python_Module("txc5", "PyTxc5");
Define_Python_Module("txc6", "PyTxc6");
Define_Python_Module("txc7", "PyTxc7");
Define_Python_Module("txc8", "PyTic8");
Define_Python_Module("txc8", "PyToc8");
Define_Python_Module("txc9", "PyTic9");
Define_Python_Module("txc9", "PyToc9");
Define_Python_Module("txc10", "PyTxc10");
Define_Python_Module("txc11", "PyTxc11");
Define_Python_Module("txc12", "PyTxc12");
Define_Python_Module("txc13", "PyTxc13");
Define_Python_Module("txc14", "PyTxc14");
Define_Python_Module("txc15", "PyTxc15");
Define_Python_Module("txc16", "PyTxc16");
Define_Python_Module("txc17", "PyTxc17");
