# source omnetpp's setenv script on login
pushd $OMNETPP_ROOT > /dev/null && source setenv && popd > /dev/null

PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h (omnetpp-dev):\w\$ "

export PYTHONPATH=$PYTHONPATH:.
export LD_LIBRARY_PATH=$OMNETPP_ROOT/lib:$OMNETPY_ROOT/lib
