on: [push]

jobs:
  build:
    steps:
      - name: "wtf"
        run: pwd && find .
      - name: "the build"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mmodenesi/omnetpy
          tags: latest
          tag_with_ref: true
